---
# @Description Build alpine
alpine-image:
  services:
    - docker:dind
  needs: []
  image: docker:stable
  stage: build
  script:
    - printenv
    - ls -all /certs/client
    # create new file in job container
    - echo "content created in CI" > ./created.txt
    # verify it exists
    - cat ./created.txt

    # build new image
    - docker build --tag dind-test .

    # spun new docker container and mount src folder under /data
    - >
      docker run
      --name ${CI_JOB_ID}
      --volume ${CI_PROJECT_DIR}/:/data/
      --interactive
      --tty
      --detach
      dind-test
      1> /dev/null

    # access files from git repo
    - docker exec ${CI_JOB_ID} cat /data/catme.txt
    # access files created in job (parent) container
    - docker exec ${CI_JOB_ID} cat /data/created.txt

  after_script:
    - docker rm -f ${CI_JOB_ID} 1> /dev/null || true
